// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUXcC3pxPhaePS4H5tiMnQEKRTxsPMdZA',
    appId: '1:949138181567:web:5ad65fbce0b72f8e30250a',
    messagingSenderId: '949138181567',
    projectId: 'livekit-calling',
    authDomain: 'livekit-calling.firebaseapp.com',
    storageBucket: 'livekit-calling.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJaMENDQIWCa4I8DKBejHUfG7pFiYy-g',
    appId: '1:949138181567:android:4b45e0b60017550b30250a',
    messagingSenderId: '949138181567',
    projectId: 'livekit-calling',
    storageBucket: 'livekit-calling.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFb7gVyl9ZjUxD5iMdLsMu8wQUQIWLb2A',
    appId: '1:949138181567:ios:27909bb5dddd3ba330250a',
    messagingSenderId: '949138181567',
    projectId: 'livekit-calling',
    storageBucket: 'livekit-calling.firebasestorage.app',
    iosBundleId: 'com.livekitCalling.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFb7gVyl9ZjUxD5iMdLsMu8wQUQIWLb2A',
    appId: '1:949138181567:ios:27909bb5dddd3ba330250a',
    messagingSenderId: '949138181567',
    projectId: 'livekit-calling',
    storageBucket: 'livekit-calling.firebasestorage.app',
    iosBundleId: 'com.livekitCalling.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUXcC3pxPhaePS4H5tiMnQEKRTxsPMdZA',
    appId: '1:949138181567:web:bb25f936f8679bc930250a',
    messagingSenderId: '949138181567',
    projectId: 'livekit-calling',
    authDomain: 'livekit-calling.firebaseapp.com',
    storageBucket: 'livekit-calling.firebasestorage.app',
  );
}
